---
version: "3"

services:
  splunk-server:
    image: "splunk/splunk:latest"
    hostname: "splunk-server"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_LICENSE_URI=free
      - SPLUNK_PASSWORD=CursoDocker2019@2
    ports:
      - "8000:8000"