# -*- mode: ruby -*-
# vi: set ft=ruby  :

machines = {
	  "manager01"         => {"memory" => "4096", "cpu" => "2", "ip" => "101", "image" => "ubuntu/bionic64"},
    #"manager02"         => {"memory" => "4096", "cpu" => "2", "ip" => "102", "image" => "centos/7"},
    "worker01"          => {"memory" => "1024", "cpu" => "2", "ip" => "104", "image" => "ubuntu/bionic64"},
    "worker02"          => {"memory" => "1024", "cpu" => "2", "ip" => "105", "image" => "ubuntu/bionic64"},
    "dtr"               => {"memory" => "1024", "cpu" => "2", "ip" => "106", "image" => "ubuntu/bionic64"},
    "monitoring-server" => {"memory" => "1024", "cpu" => "2", "ip" => "150", "image" => "ubuntu/bionic64"},
}

Vagrant.configure("2") do |config|

  config.vm.box_check_update = false
  config.vm.boot_timeout = 600
  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}.dexter.com.br"
      machine.vm.network "private_network", ip: "200.100.50.#{conf["ip"]}", :name => 'vboxnet1'
      #machine.vm.network "forwarded_port", guest: 8000, host: 8000, protocol: "tcp", guest: 80, host: 8080, protocol: "tcp"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        #vb.customize ["modifyvm", :id, "--groups", "/lab_k8s"]
        machine.vm.provision "shell", inline: "hostnamectl set-hostname #{name}.dexter.com.br"
        #machine.vm.provision "shell", path: "arquivos/script.sh"
        machine.vm.provision "ansible" do |ansible|
          ansible.groups = {
            "ubuntus" => ["#{name}"],
            "centos" => ["manager02"],
          }
        ansible.playbook = "provision/playbook-ubuntu.yaml"
        #ansible.playbook = "provision/playbook-centos.yaml"
        #machine.vm.provision "shell", inline: "sudo docker-compose run -d splunk-server" 
        machine.vm.provision "shell", path: "arquivos/script.sh" 
      end    
        end
        end    
    end
  end