# -*- mode: ruby -*-
# vi: set ft=ruby  :

machines = {
	"manager01"         => {"memory" => "4096", "cpu" => "2", "ip" => "101", "image" => "ubuntu/bionic64"},
   #"manager02"         => {"memory" => "4096", "cpu" => "2", "ip" => "102", "image" => "centos/7"},
    "worker01"          => {"memory" => "1024", "cpu" => "2", "ip" => "104", "image" => "ubuntu/bionic64"},
    "worker02"          => {"memory" => "1024", "cpu" => "2", "ip" => "105", "image" => "centos/7"},
    "dtr"               => {"memory" => "1024", "cpu" => "2", "ip" => "106", "image" => "ubuntu/bionic64"},
    "monitoring-server" => {"memory" => "1024", "cpu" => "2", "ip" => "150", "image" => "ubuntu/bionic64"},

}

Vagrant.configure("2") do |config|

  config.vm.box_check_update = false
  config.vm.boot_timeout = 600
  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}.dexter.com.br"
      machine.vm.network "private_network", ip: "200.100.50.#{conf["ip"]}", :name => 'vboxnet1'
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        #vb.customize ["modifyvm", :id, "--groups", "/lab_k8s"]
      end
       if "#{conf["image"]}" == "ubuntu/bionic64"
         machine.vm.provision "shell", inline: "apt-get update ; hostnamectl set-hostname #{name}.dexter.com.br"
       end
    end
  end
  config.vm.provision "shell", path: "../arquivos/script.sh"
end