---
- hosts: centos
  become: true
  tasks:
    - name: Add the user 'centuser' with a specific uid and a primary group of 'admin'
      user:
        name: centuser
        password: senha123
        comment: centuser
        shell: /bin/bash

    - name: Create a 2048-bit SSH key for user centuser in ~/.ssh/id_rsa
      user:
        name: centuser
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    